Init script now provides error messages when input .tar file cannot be found.
git-svn-id: https://sst-simulator.googlecode.com/svn/qsim/trunk@2834 9770eb50-c74b-b24d-123c-4e78d768fe5e

diff --git a/initrd/init b/initrd/init
--- a/initrd/init
+++ b/initrd/init
@@ -23,6 +23,14 @@ cd data
 
 /sbin/qsim_in > extractme.tar
 tar -xvf extractme.tar
+if [ $? != 0 ]; then
+  echo Untar input failed. Are you providing a .tar archive? | /sbin/qsim_out
+fi
+
+if [ -ne runme.sh ]; then
+  echo \"runme.sh\" not found. Input .tar must contain this. | /sbin/qsim_out
+fi
+
 /sbin/chmod +x ./runme.sh
 ./runme.sh 2>&1 | /sbin/qsim_out
 
